### ISSUE TITLE
windows

### ISSUE THREAD

**Issue by rozhandad** [Raguggg/colab-as-Vps#5]
Hello
Thank you for this program
Do you have a code that will give us windows server instead of ubuntu?

**Comment by Raguggg** [comment]
Hi,

Colab runs on Linux, so it is not possible to run Windows on it. To use Windows, we would need to access the boot manager, but unfortunately, this is not possible. Additionally, virtual machines are not supported because graphics are disabled. To enable graphics, we would need to access the boot window, which is also not possible.
